apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: node-mongo-app
spec:
  # 3 Pods should exist at all times.
  replicas: 2
  selector:
    matchLabels:
      app: nodebd-app
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: nodebd-app
    spec:
      containers:
      - name: nodebd-app-c1
        # Run this image
        image: philippaul/node-mongo-db:02
      - name: mongobd-app-c1
        # Run this image
        image: mongo:latest
